---
title: "Additive_phenomenon_for_incidence"
author: "Jakub"
date: "16 listopadu 2016"
output: html_document
---


```{r include=FALSE, cache=TRUE}
library(deSolve)
library(plyr)

options("scipen" = 10)

# initial state:
N <- 1
prop <- 0.01 #initial value of Iw and Iz

# time:
a <- 2000 #time span for initial value
a_init <- 2000

m <- 1 #time step

zoom <- 100 #after breakpoint 1/zoom step
time_to_change <- 5 #time interval separating two sequential changes of AMU
a_end <- 2800  #end of study = 300 steps after beginning of intervention





# parameters
pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

#epsilon change over time

peps <- 0.10 #initial value of the ratio of treated patients
pepsi <- seq(0.11,0.2,by=0.01) #variation of epsilon




```


```{r stable, include=FALSE, cache=TRUE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop, dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

times=seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       { dnewcasesIz=beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw
         dnewcasesIw=beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz
         dsecondaryres=rho*eps*Iw
         dprimaryres=beta_z*Iz*S + eps*beta_z*Iz*Iw
         dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        list(c(dS, dIw, dIz, dnewcasesIz, dnewcasesIw, dsecondaryres, dprimaryres))
       })
}

out_init=as.data.frame(
  ode(y=state, times=times, func=SIS, parms=parameters)
)

```

```{r incidence, include=FALSE, cache=TRUE}
#allows to calculate daily incidence
incid = function(x, zoom) {
  der <- rep(0, length(x))
  for (i in 2:length(x)) {
    der[i] <- x[i]-x[i-1]
  }
  der_day <- rep(0, round(length(der)/zoom))
  for (i in 1:round(length(der)/zoom)) {
    der_day[i] <- sum(der[((i-1)*zoom):(i*zoom)])
  }
  return(der_day)
}
```

```{r additiv_pheno, echo=FALSE, fig.align='center', cache=TRUE}

out_fast_var <- out_init



states_at_breaks <- out_init[nrow(out_init),]
for (i in 1:length(pepsi)) {
  state3 <- c(S=out_fast_var$S[nrow(out_fast_var)], Iw=out_fast_var$Iw[nrow(out_fast_var)], Iz=out_fast_var$Iz[nrow(out_fast_var)], Iwz=out_fast_var$Iwz[nrow(out_fast_var)], dnewcasesIz=out_fast_var$dnewcasesIz[nrow(out_fast_var)], dnewcasesIw=out_fast_var$dnewcasesIw[nrow(out_fast_var)], dsecondaryres=out_fast_var$dsecondaryres[nrow(out_fast_var)], dprimaryres=out_fast_var$dprimaryres[nrow(out_fast_var)])
  parameters[5] <-pepsi[i]
  times3=seq(out_fast_var[nrow(out_fast_var),1] + m/zoom, out_fast_var[nrow(out_fast_var),1] + time_to_change, by = m/zoom)
  out<- as.data.frame(
    ode(y=state3, times=times3, func=SIS, parms=parameters)
    )
  out_fast_var <- rbind(out_fast_var, out)
  states_at_breaks <- rbind(states_at_breaks, out[nrow(out),])
  }


#evolution after all interventions
state3 <- c(S=out_fast_var$S[nrow(out_fast_var)], Iw=out_fast_var$Iw[nrow(out_fast_var)], Iz=out_fast_var$Iz[nrow(out_fast_var)], Iwz=out_fast_var$Iwz[nrow(out_fast_var)], dnewcasesIz=out_fast_var$dnewcasesIz[nrow(out_fast_var)], dnewcasesIw=out_fast_var$dnewcasesIw[nrow(out_fast_var)], dsecondaryres=out_fast_var$dsecondaryres[nrow(out_fast_var)], dprimaryres=out_fast_var$dprimaryres[nrow(out_fast_var)])
parameters[5] <-pepsi[length(pepsi)]
times3=seq(states_at_breaks[nrow(states_at_breaks),1] + m/zoom, a_end, by=(m/zoom))
out<- as.data.frame(
  ode(y=state3, times=times3, func=SIS, parms=parameters)
)
out_fast_var <- rbind(out_fast_var, out)

states_at_breaks <- states_at_breaks[2:nrow(states_at_breaks),]
states_at_breaks <- cbind(states_at_breaks, cbind(pepsi))
  
```





```{r control, include=FALSE, cache=TRUE}

controlfunc <- function(states, a_end) {
  state3 <- c(S=states[2], Iw=states[3], Iz=states[4], dnewcasesIz=states[5], dnewcasesIw=states[6], dsecondaryres=states[7], dprimaryres=states[8])
  parameters[5] <- states[9]
  times3=seq(states[1] + m/zoom, a_end, by=m/zoom)
  out <- as.data.frame(
  ode(y=state3, times=times3, func=SIS, parms=parameters)
  )
}


cbind.fill <- function(...){
    nm <- list(...) 
    nm <- lapply(nm, as.matrix)
    n <- max(sapply(nm, nrow)) 
    do.call(cbind, lapply(nm, function (x) 
        rbind(x, matrix(, n-nrow(x), ncol(x))))) 
}

states_at_breaks <- as.data.frame(t(states_at_breaks))



out_control <- do.call(cbind.fill, lapply(states_at_breaks, controlfunc, a_end))

#replacing NA in control with data from the main model
repl_NA <- function(controldata, expdata) {
  print(as.numeric(parent.frame()$i))
}

out_control <- as.data.frame(out_control)



```

```{r control_without_additph, include=FALSE, cache=TRUE}

states4 <- c(S=out_init[nrow(out_init), 2], Iw=out_init[nrow(out_init), 3], Iz=out_init[nrow(out_init), 4], dnewcasesIz=out_init[nrow(out_init), 5], dnewcasesIw=out_init[nrow(out_init), 6], dsecondaryres=out_init[nrow(out_init), 7], dprimaryres=out_init[nrow(out_init), 8])
parameters[5] <- pepsi[length(pepsi)]
times4 <- seq(out_init[nrow(out_init), 1], a_end, by=m/zoom)


out_control2 <- as.data.frame(
  ode(y=states4, times=times4, func=SIS, parms=parameters)
  )



```

```{r incid_prep_plot, echo=FALSE, fig.align='center', cache=TRUE}
#plotting incidence

out_fast_var <- out_fast_var[2001:nrow(out_fast_var),]

out <- cbind.fill(out_fast_var, out_control, out_control2)

#selecting numbers of columns in the out for twenty values of eps after intervention : first=experiment + control
nnewiz <- seq(5,ncol(out), by=8)
nnewiw <- seq(6,ncol(out), by=8)
nnewsec <- seq(7,ncol(out), by=8)
nnewprim <- seq(8,ncol(out), by=8)



#selecting columns for each incidence type
NewIz <- out[,nnewiz]
NewIw <- out[,nnewiw]
Newsec <- out[,nnewsec]
Newprim <- out[,nnewprim]

#calculating incidence
NewIz <- apply(NewIz, 2, incid, zoom)
NewIw <- apply(NewIw, 2, incid, zoom)
Newsec <- apply(Newsec, 2, incid, zoom)
Newprim <- apply(Newprim, 2, incid, zoom)

Newp <- NewIz/(NewIz+NewIw)

#putting NA at the beginning of the column for the controls

for (i in 1:10) {
  NewIz[,i+1] <- c(NewIz[(nrow(NewIz)-i*time_to_change+1):nrow(NewIz),i+1], NewIz[1:(nrow(NewIz)-i*time_to_change),i+1])
  
  NewIw[,i+1] <- c(NewIw[(nrow(NewIw)-i*time_to_change+1):nrow(NewIw),i+1], NewIw[1:(nrow(NewIw)-i*time_to_change),i+1])
  Newsec[,i+1] <- c(Newsec[(nrow(Newsec)-i*time_to_change+1):nrow(Newsec),i+1], Newsec[1:(nrow(Newsec)-i*time_to_change),i+1])
  
  Newprim[,i+1] <- c(Newprim[(nrow(Newprim)-i*time_to_change+1):nrow(Newprim),i+1], Newprim[1:(nrow(Newprim)-i*time_to_change),i+1])
  
  Newp[,i+1] <- c(Newp[(nrow(Newp)-i*time_to_change+1):nrow(Newp),i+1], Newp[1:(nrow(Newp)-i*time_to_change),i+1])
                      }

#timespan of testing
t2 <- seq(1, a_end-a_init)

colglob <- colorRampPalette(c("blue", "red"))

colforcol <- colglob(ncol((NewIw)-1))

#timespan of testing : control
linfun <- function(x, t){
  lines(t, unlist(x), lty=2, lwd=2, col=colforcol[as.numeric(parent.frame()$i)])
}

```


```{r incid_plot_Iw, echo=FALSE, fig.align='center', cache=TRUE}
#Iw
plot(t2, NewIw[,1], main="Incidence of susceptible infections \n after a change in AMU", xlab="time (steps)", ylab="Incidence Iw", ylim=c(0,0.011), lty=1, lwd=2, type="l")

capture.output(apply(NewIw[,2:(ncol(NewIw)-1)], 2, linfun, t2),file='NUL')
lines(t2, NewIw[,ncol(NewIw)], lty=1, lwd=2, col="red")

legend("topright" , inset=.05, title="AMU" ,c("20%", "11%"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))
```

```{r incid_plot_Iz, echo=FALSE, fig.align='center', cache=TRUE}

plot(t2, NewIz[,1], main="Incidence of resitant infections \n after a change in AMU", xlab="time (steps)", ylab="Incidence Iz", ylim=c(0,0.011), lty=1, lwd=2, type="l")

capture.output(apply(NewIz[,2:(ncol(NewIz)-1)], 2, linfun, t2), file='NUL')

lines(t2, NewIz[,ncol(NewIz)], lty=1, lwd=2, col="red")

legend("topright" , inset=.05, title="AMU" ,c("20%", "11%"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))
```

```{r incid_plot_prim, echo=FALSE, fig.align='center', cache=TRUE}
plot(t2, Newprim[,1], main="Incidence of primary resistance \n after a change in AMU", xlab="time (steps)", ylab="new primary Iz", ylim=c(0,0.004), lty=1, lwd=2, type="l")

capture.output(apply(Newprim[,2:(ncol(Newprim)-1)], 2, linfun, t2), file='NUL')

lines(t2, Newprim[,ncol(Newprim)], lty=1, lwd=2, col="red")

legend("topright" , inset=.05, title="AMU" ,c("20%", "11%"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

```

```{r incid_plot_sec, echo=FALSE, fig.align='center', cache=TRUE}
#Sec
plot(t2, Newsec[,1], main="Incidence of secondary resistance \n after a change in AMU", xlab="time (steps)", ylab="new secondary Iz", ylim=c(0,0.004), lty=1, lwd=2, type="l")

capture.output(apply(Newsec[,2:(ncol(Newsec)-1)], 2, linfun, t2), file='NUL')

lines(t2, Newsec[,ncol(Newsec)], lty=1, lwd=2, col="red")

legend("topright" , inset=.05, title="AMU" ,c("20%", "11%"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


```


```{r incid_plot_p, echo=FALSE, fig.align='center', cache=TRUE}
#p
plot(t2, Newp[,1], main="Estimated p after a change in AMU", xlab="time (steps)", ylab="p", ylim=c(0,1), lty=1, lwd=2, type="l")

capture.output(apply(Newp[,2:(ncol(Newp)-1)], 2, linfun, t2), file='NUL')

lines(t2, Newp[,ncol(Newp)], lty=1, lwd=2, col="red")

legend("topright" , inset=.05, title="AMU" ,c("20%", "11%"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

```


