---
title: "Impact of AMU variation on prevalence"
author: "Jakub"
date: "15 listopadu 2016"
output: html_document
---

```{r parameters, include=FALSE}
library(deSolve)


options("scipen" = 10)

# initial state:
N <- 1
prop <- 0.01 #initial value of Iw and Iz

# time:
a <- 2000 #time span
m <- 1 #time step

zoom <- 100 #after breakpoint 1/zoom step
zoom_area <- 2000 #time span after breakpoint

zooming <- 200 #zooming after break point

# parameters
pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

#epsilon change over time

peps <- 0.10 #initial value of the ratio of treated patients
pepsi <- seq(0,0.2,by=0.01) #variation of epsilon
peps_inc <- 0.15 #increased value of epsilon for trial
peps_dec <- 0.05 #decreased value of epsilon for trial



```



<center> <h2> Change in the proportion of treated patients </h2> </center>

 
 
 
```{r stable, include=FALSE, warning = FALSE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop, dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

times=seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       { dnewcasesIz=beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw
         dnewcasesIw=beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz
         dsecondaryres=rho*eps*Iw
         dprimaryres=beta_z*Iz*S + eps*beta_z*Iz*Iw
         dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        list(c(dS, dIw, dIz, dnewcasesIz, dnewcasesIw, dsecondaryres, dprimaryres))
       })
}

out_init=as.data.frame(
  ode(y=state, times=times, func=SIS, parms=parameters)
)

```

```{r multiple_var, include=FALSE, cache=TRUE, warning = FALSE}


parameters3 <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps_dec, rho=prho)


times3=seq(a, a+zoom_area, by=m/zoom)

state3 <- c(S=out_init$S[a+1], Iw=out_init$Iw[a+1], Iz=out_init$Iz[a+1], Iwz=out_init$Iwz[a+1], dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

break_point=function(x){
  parameters3[5] <-x
  out_multi=as.data.frame(
  ode(y=state3, times=times3, func=SIS, parms=parameters3))
  return(out_multi)
}

pepsi <- seq(0, 0.2, by=0.01)

out <- do.call(cbind, lapply(pepsi,break_point))

```


```{r assist_func, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

colglob <- colorRampPalette(c("blue", "red"))

colforcol <- colglob(length(pepsi))


linfun <- function(x, t){
  lines(t, unlist(x), lty=1, lwd=2, col=colforcol[as.numeric(parent.frame()$i)])
}

```

```{r plot_prep_multi_var, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

t<- seq(0, zoom_area, by=m/zoom)


#sorting columns into distinct subpopulations

ns <- seq(2,ncol(out), by=8)
niw <- seq(3,ncol(out), by=8)
niz <- seq(4,ncol(out), by=8)

#selecting these columns

S <- out[,ns]
colnames(S) <- seq(0,0.2,by=0.01)

Iw <- out[,niw]
Iz <- out[,niz]


```

```{r deriv_func, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}
incid = function(x, zoom) {
  der <- rep(0, length(x))
  for (i in 2:length(x)) {
    der[i] <- x[i]-x[i-1]
  }
  der_day <- rep(0, round(length(der)/zoom))
  for (i in 1:round(length(der)/zoom)) {
    der_day[i] <- sum(der[((i-1)*zoom):(i*zoom)])
  }
  return(der_day)
}


```

```{r deriv, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

S_der <- apply(S, 2, incid, zoom)
Iw_der <- apply(Iw, 2, incid, zoom)
Iz_der <- apply(Iz, 2, incid, zoom)


```

```{r plot_prev_S, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}
#plotting S
plot(t, S[,11], main="Evolution of Susceptible population after a variation of epsilon", xlab="time (steps)", ylab="S ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

capture.output(apply(S, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

t2 <- seq(1, zoom_area, by=m)
#plotting S derivative with respect to time
plot(t2, S_der[,11], main="Derivative of Susceptible population after a variation of epsilon", xlab="time (steps)", ylab="S ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(S_der, 2, linfun, t2), file='NUL')

legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


S_der_zoom <- S_der[1:(zooming*m+1),]
t3 <- seq(0, zooming)

#plotting zoomed S derivative with respect to time
plot(t3, S_der_zoom[,11], main="Derivative of Susceptible population after a variation of epsilon", xlab="time (steps)", ylab="S ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(S_der_zoom, 2, linfun, t3), file='NUL')

legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))
```

```{r plot_prev_Iw, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting Iw
plot(t, Iw[,11], main="Evolution of population infected with sensitive strain after a variation of epsilon", xlab="time (steps)", ylab="Iw ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

capture.output(apply(Iw, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

plot(t2, Iw_der[,11], main="Derivative of population infected with sensitive strain after a variation of epsilon", xlab="time (steps)", ylab="Iw ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(Iw_der, 2, linfun, t2), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


Iw_der_zoom <- Iw_der[1:(zooming*m+1),]


#plotting zoomed Iw derivative with respect to time
plot(t3, Iw_der_zoom[,11], main="Derivative of population infected with sensitive strain after a variation of epsilon", xlab="time (steps)", ylab="Iw ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(Iw_der_zoom, 2, linfun, t3), file='NUL')

legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))
```

```{r plot_prev_Iz, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting Iz
plot(t, Iz[,11], main="Evolution of population infected with resistant strain after a variation of epsilon", xlab="time (steps)", ylab="Iz ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

capture.output(apply(Iz, 2, linfun, t), file='NUL')



legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

plot(t2, Iz_der[,11], main="Derivative of population infected with resistant strain after a variation of epsilon", xlab="time (steps)", ylab="Iz ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(Iz_der, 2, linfun, t2), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

Iz_der_zoom <- Iz_der[1:(zooming*m+1),]


#plotting zoomed Iw derivative with respect to time
plot(t3, Iz_der_zoom[,11], main="Derivative of population infected with resistant strain after a variation of epsilon", xlab="time (steps)", ylab="Iz ratio derivative", ylim=c(-0.005,0.005), lty=1, lwd=2, type="l")

capture.output(apply(Iz_der_zoom, 2, linfun, t3), file='NUL')

legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

```


```{r plot_prev_p, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting p
Ratio <- as.matrix(Iz)/(as.matrix(Iz)+as.matrix(Iw))

plot(t, Ratio[,11], main="Evolution of P ratio - prevalence", xlab="time (steps)", ylab="P", ylim=c(0,1), lty=1, lwd=2, type="l")

capture.output(apply(Ratio, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))

epsvar <- seq(0, 0.2, by=0.01)

p_steady <- Ratio[nrow(Ratio),]

plot(epsvar, p_steady, main="Evolution of P ratio - prevalence", xlab=expression(epsilon), ylab="P", ylim=c(0,1), lty=1, lwd=2, type="l")


```


```{r plot_prod_S_Iw, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting S Iw mass product
prod_S_Iw <- S*Iw

plot(t, prod_S_Iw[,11], main="Evolution of S*Iw after a change in epsilon", xlab="time (steps)", ylab="S*Iw", ylim=c(0,0.3), lty=1, lwd=2, type="l")

capture.output(apply(prod_S_Iw, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


```

```{r plot_prod_S_Iz, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting S Iz mass product
prod_S_Iz <- S*Iz

plot(t, prod_S_Iz[,11], main="Evolution of S*Iz after a change in epsilon", xlab="time (steps)", ylab="S*Iz", ylim=c(0,0.3), lty=1, lwd=2, type="l")

capture.output(apply(prod_S_Iz, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


```

```{r plot_prod_Iw_Iz, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

#plotting Iw Iz mass product
prod_Iw_Iz <- Iw*Iz

plot(t, prod_Iw_Iz[,11], main="Evolution of Iw*Iz after a change in epsilon", xlab="time (steps)", ylab="Iw*Iz", ylim=c(0,0.3), lty=1, lwd=2, type="l")

capture.output(apply(prod_Iw_Iz, 2, linfun, t), file='NUL')


legend("topleft" , inset=.05, c("eps=0.20", "eps=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


```

```{r steady_state_Q, echo=FALSE, fig.align='center', cache=TRUE, warning = FALSE}

Iz_ss <- Iz[nrow(Iz),]
Iw_ss <- Iw[nrow(Iw),]
Q_ss_Iw <- Iw_ss*epsvar
Q_ss_Iw_Iz <- (Iw_ss+Iz_ss)*epsvar

Q_ss_Iw <- as.matrix(Q_ss_Iw)
Q_ss_Iw_Iz <- as.matrix(Q_ss_Iw_Iz)

plot(Q_ss_Iw, p_steady, main="Evolution of P ratio - prevalence, Iw treated", xlab="E", ylab="P", ylim=c(0,1), col='red', type = 'l', lty=1, lwd=2)


plot(Q_ss_Iw_Iz, p_steady, main="Evolution of P ratio - prevalence, all treated", xlab="E", ylab="P", ylim=c(0,1), lwd=2, col='red', lty=1, type = 'l')

#burden of infection

burd <- Iw_ss+Iz_ss

plot(Q_ss_Iw, burd, main="Evolution of burden of infection - Iw treated", xlab="E", ylab="Burden of Infection", ylim=c(0,1), col='red', type = 'l', lty=1, lwd=2)

plot(Q_ss_Iw_Iz, burd, main="Evolution of burden of infection - all treated", xlab="E", ylab="Burden of Infection", ylim=c(0,1), col='red', type = 'l', lty=1, lwd=2)

#Q as fn of epsilon

plot(epsvar, Q_ss_Iw, main="Evolution of E, Iw treated", xlab=expression(epsilon), ylab="E", ylim=c(0,0.1), lwd=2, col='red', lty=1, type = 'l')

plot(epsvar, Q_ss_Iw_Iz, main="Evolution of E, all treated", xlab=expression(epsilon), ylab="E", ylim=c(0,0.1), lwd=2, col='red', lty=1, type = 'l')

```
