---
title: "Change in ATB consumption"
author: "Jakub"
date: "18 října 2016"
output: html_document
---


```{r include=FALSE}
library(deSolve)


options("scipen" = 10)

# initial state:
N <- 1
prop <- 0.01 #initial value of Iw and Iz

# time:
a <- 2000 #time span
m <- 1 #time step

zoom <- 100 #after breakpoint 1/zoom step
zoom_area <- 2000 #time span after breakpoint


# parameters
pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

#epsilon change over time

peps <- 0.10 #initial value of the ratio of treated patients
pepsi <- seq(0,0.2,by=0.01) #variation of epsilon
peps_inc <- 0.15 #increased value of epsilon for trial
peps_dec <- 0.05 #decreased value of epsilon for trial



```



<center> <h2> Change in the proportion of treated patients </h2> </center>

 
 
 
```{r stable, include=FALSE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop, dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

times=seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       { dnewcasesIz=beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw
         dnewcasesIw=beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz
         dsecondaryres=rho*eps*Iw
         dprimaryres=beta_z*Iz*S + eps*beta_z*Iz*Iw
         dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        list(c(dS, dIw, dIz, dnewcasesIz, dnewcasesIw, dsecondaryres, dprimaryres))
       })
}

out_init=as.data.frame(
  ode(y=state, times=times, func=SIS, parms=parameters)
)

```


```{r increase, include=FALSE, cache=TRUE}
parameters2 <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps_inc, rho=prho)

state2 <- c(S=out_init$S[a+1], Iw=out_init$Iw[a+1], Iz=out_init$Iz[a+1], dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0 )

times2=seq(a, a+zoom_area, by=m/zoom)

out_inc=as.data.frame(
  ode(y=state2, times=times2, func=SIS, parms=parameters2)
)

```

```{r decrease, include=FALSE, cache=TRUE}


parameters3 <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps_dec, rho=prho)

state2 <- c(S=out_init$S[a+1], Iw=out_init$Iw[a+1], Iz=out_init$Iz[a+1], Iwz=out_init$Iwz[a+1], dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

times2=seq(a, a+zoom_area, by=m/zoom)

out_dec=as.data.frame(
  ode(y=state2, times=times2, func=SIS, parms=parameters3)
)

```


```{r plot, echo=FALSE, fig.align='center'}


inc <- rbind(out_init[1:a,], out_inc)
dec <- rbind(out_init[1:a,], out_dec)
t<- c(seq(0, a, by=m), seq(a+m/zoom, a+zoom_area, by=m/zoom))

plot(t, inc$Iw, main="Change of epsilon", xlab="time (steps)", ylab="ratio", ylim=c(0,1), lty=3, lwd=2, type="l", col="RED")

lines(t, dec$Iw, lty=3, lwd=2, col="BLUE")
lines(t, inc$Iz, lty=2, lwd=2, col="RED")
lines(t, dec$Iz, lty=2, lwd=2, col="BLUE")

legend("topleft" , inset=.05, c("Iw Sensitive strain", "Iz Resistant strain"), lty=c(3,2), lwd=c(3,2))
```


```{r multiple_var, include=FALSE, cache=TRUE}


parameters3 <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps_dec, rho=prho)


times3=seq(a, a+zoom_area, by=m/zoom)

state3 <- c(S=out_init$S[a+1], Iw=out_init$Iw[a+1], Iz=out_init$Iz[a+1], Iwz=out_init$Iwz[a+1], dnewcasesIz=0, dnewcasesIw=0, dsecondaryres=0, dprimaryres=0)

break_point=function(x){
  parameters3[5] <-x
  out_multi=as.data.frame(
  ode(y=state3, times=times3, func=SIS, parms=parameters3))
  return(out_multi)
}

pepsi <- seq(0, 0.2, by=0.01)

out <- do.call(cbind, lapply(pepsi,break_point))

```

```{r plot_multi_var, echo=FALSE, fig.align='center'}


t<- seq(a, a+2000, by=m/zoom)

colglob <- colorRampPalette(c("blue", "red"))

colforcol <- colglob(length(pepsi))


linfun <- function(x){
  lines(t, unlist(x), lty=1, lwd=2, col=colforcol[as.numeric(parent.frame()$i)])
}




ns <- seq(2,ncol(out), by=8)
niw <- seq(3,ncol(out), by=8)
niz <- seq(4,ncol(out), by=8)





S <- out[,ns]
colnames(S) <- seq(0,0.2,by=0.01)

Iw <- out[,niw]
Iz <- out[,niz]




plot(t, S[,11], main="Evolution of Susceptible population after a variation of  ATB usage", xlab="time (steps)", ylab="S ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

apply(S, 2, linfun)


legend("topleft" , inset=.05, c("epsilon=0.20", "epsilon=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))




plot(t, Iw[,11], main="Evolution of population infected with sensitive strain after a variation of  ATB usage", xlab="time (steps)", ylab="Iw ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

apply(Iw, 2, linfun)


legend("topleft" , inset=.05, c("epsilon=0.20", "epsilon=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


plot(t, Iz[,11], main="Evolution of population infected with resistant strain after a variation of  ATB usage", xlab="time (steps)", ylab="Iz ratio", ylim=c(0,1), lty=1, lwd=2, type="l")

apply(Iz, 2, linfun)


legend("topleft" , inset=.05, c("epsilon=0.20", "epsilon=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


Ratio <- as.matrix(Iz)/(as.matrix(Iz)+as.matrix(Iw))

plot(t, Ratio[,11], main="Evolution of p after a change in ATB usage", xlab="time (steps)", ylab="p", ylim=c(0,1.5), lty=1, lwd=2, type="l")

apply(Ratio, 2, linfun)


legend("topleft" , inset=.05, c("epsilon=0.20", "epsilon=0"), lty=c(1,1), lwd=c(2,2), col=c("red", "blue"))


```



```{r incidence, include=FALSE, cache=TRUE}
#incid function allows to calculate daily incidence by substracting a value of a varible from its value after following step and by summing these differences over a time corresponding to one day (id over zoom days) 
incid = function(x, zoom) {
  der <- rep(0, length(x))
  for (i in 2:length(x)) {
    der[i] <- x[i]-x[i-1]
  }
  der_day <- rep(0, round(length(der)/zoom))
  for (i in 1:round(length(der)/zoom)) {
    der_day[i] <- sum(der[((i-1)*zoom):(i*zoom)])
  }
  return(der_day)
}


```

```{r incid_plot, include=FALSE}
nnewiz <- seq(5,ncol(out), by=8)
nnewiw <- seq(6,ncol(out), by=8)
nnewsec <- seq(7,ncol(out), by=8)
nnewprim <- seq(8,ncol(out), by=8)



NewIz <- out[,nnewiz]
NewIw <- out[,nnewiw]
Newsec <- out[,nnewsec]
Newprim <- out[,nnewprim]

NewIz <- apply(NewIz, 2, incid, zoom)
NewIw <- apply(NewIw, 2, incid, zoom)
Newsec <- apply(Newsec, 2, incid, zoom)
Newprim <- apply(Newprim, 2, incid, zoom)

t2 <- seq(1, 2000)

linfun2 <- function(x){
  lines(t2, unlist(x), lty=1, lwd=2, col=colforcol[as.numeric(parent.frame()$i)])
}



plot(t2, NewIz[,11], main="New cases of resitant infections after a change in ATB usage", xlab="time (steps)", ylab="new Iz", ylim=c(0,0.011), lty=1, lwd=2, type="l")

apply(NewIz, 2, linfun2)

plot(t2, NewIw[,11], main="New cases of susceptible infections after a change in ATB usage", xlab="time (steps)", ylab="new Iw", ylim=c(0,0.011), lty=1, lwd=2, type="l")

apply(NewIw, 2, linfun2)

plot(t2, Newsec[,11], main="New cases of secondary resistance after a change in ATB usage", xlab="time (steps)", ylab="new secondary Iz", ylim=c(0,0.004), lty=1, lwd=2, type="l")

apply(Newsec, 2, linfun2)

plot(t2, Newprim[,11], main="New cases of primary resistance after a change in ATB usage", xlab="time (steps)", ylab="new primary Iz", ylim=c(0,0.004), lty=1, lwd=2, type="l")

apply(Newprim, 2, linfun2)

Newp <- NewIz/(NewIz+NewIw)

plot(t2, Newp[,11], main="Estimated p after a change in ATB usage", xlab="time (steps)", ylab="p", ylim=c(0,1), lty=1, lwd=2, type="l")

apply(Newp, 2, linfun2)


```