---
title: "inertie_study_time_to_equilibrium"
author: "Jakub"
date: "12 prosince 2016"
output: html_document
---



```{r include=FALSE}
library(deSolve)


options("scipen" = 10)

# initial state:
N <- 1
prop <- 0.01 #initial value of Iw and Iz

# time:
a <- 200000 #time span
m <- 1 #time step



# parameters
pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

#epsilon change over time

peps <- 0 #initial value of the ratio of treated patients
delta_eps <- 0.01
pepsi <- seq(0,0.2,by=delta_eps) #variation of epsilon



conv_crit <- 0.000001

```

```{r initial_ss, include=FALSE, cache=TRUE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times=seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       { 
         dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        
        list(c(dS, dIw, dIz))
       })
}


parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_eps=function(x) {
  parameters[5] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_eps <- do.call(rbind, lapply(pepsi, exploit_param_eps))
steady_eps <- unlist(steady_eps)

steady_time_eps <- steady_eps[,1]
steady_S_eps <- steady_eps[,2]
steady_Iw_eps <- steady_eps[,3]
steady_Iz_eps <- steady_eps[,4]
steady_p_eps <- steady_eps[,4]/(steady_eps[,4]+steady_eps[,3])

table_ss <- cbind(steady_S_eps, steady_Iw_eps, steady_Iz_eps)
```


```{r initial_ss_plot, echo=FALSE, cache=TRUE}
plot(pepsi, steady_Iz_eps, main="Starting with a steady state \n corresponding to eps=0.20", xlab="AMU", ylab="proportion", ylim=c(0,1), lty=2, lwd=2, type="l", col='red')
lines(pepsi, steady_Iw_eps, lty=3, lwd=2, type='l', col='red')
lines(pepsi, steady_S_eps, lty=1, lwd=2, type='l', col='red')
lines(pepsi, steady_p_eps, lty=1, lwd=2, type='l', col='black')


legend("bottomleft" , inset=.05, c("S", "Iz", "Iw", "p"), lty=c(1,2,3,1), lwd=c(2,2,2,2), col=c(rep('red',3), 'black'))
```


```{r initial_ss_tables_prep, echo=FALSE, cache=TRUE}


change_up_ss <- matrix(c(unlist(table_ss[1:(nrow(table_ss)-2),]), seq(delta_eps, (0.20-delta_eps), by=delta_eps)), ncol=4)

change_down_ss <- matrix(c(unlist(table_ss[3:(nrow(table_ss)),]), seq(delta_eps, 0.20-delta_eps, by=delta_eps)), ncol=4)
```

```{r time_to_stabilization, echo=FALSE}
#somehow doesn't work, I cannot subset in apply...


#time_to_change=function(x) {
#  parameters[5] <- x[4]
#  state[1] <- x[1]
#  state[2] <- x[2]
#  state[3] <- x[3]
#  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
#  return(tail(out, n=1))
#}

#change_up_ss <- matrix(unlist(change_up_ss), ncol=4)

#out_up <- apply(change_up_ss, 1, time_to_change)


#out_up <- do.call(rbind, apply(change_up_ss2, 1, time_to_change))

#out_up <- do.call(rbind, apply(change_up_ss, 1, time_to_change))
#out_down <- do.call(rbind, apply(change_down_ss, 1, time_to_change))


out_up <- rep(0,4)

for (i in 1:nrow(change_up_ss)) {
  parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)
  state <- c(S=1-2*prop, Iw=prop, Iz=prop)
  parameters[5] <- change_up_ss[i,4]
  state[1] <- change_up_ss[i,1]
  state[2] <- change_up_ss[i,2]
  state[3] <- change_up_ss[i,3]
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  out_up <- rbind(out_up, tail(out,1))
}

out_down <- rep(0,4)

for (i in 1:nrow(change_down_ss)) {
  parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)
  state <- c(S=1-2*prop, Iw=prop, Iz=prop)
  parameters[5] <- change_down_ss[i,4]
  state[1] <- change_down_ss[i,1]
  state[2] <- change_down_ss[i,2]
  state[3] <- change_down_ss[i,3]
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  out_down <- rbind(out_down, tail(out,1))
}



```

```{r time_to_stabilization_plot, echo=FALSE}


time_up <- out_up[2:nrow(out_up),1]

time_down <- out_down[2:nrow(out_down),1]

pepsi_change <- seq(delta_eps, (0.20-delta_eps), by=delta_eps)

plot(pepsi_change, time_up, main="Inertia", xlab="proportion of treated patients", ylab="time to stabilization", lwd=2, col='red', type='l')
lines(pepsi_change, time_down, lwd=2, col='blue', type='l')

legend("bottomleft" , inset=.05, c("Increasing eps", "Decreasing eps"), lwd=c(2,2), col=c('red', 'blue'))
```








```{r include=FALSE}
library(deSolve)


options("scipen" = 10)

# initial state:
N <- 1
prop <- 0.01 #initial value of Iw and Iz

# time:
a <- 200000 #time span
m <- 1 #time step



# parameters
pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

#epsilon change over time

peps <- 0 #initial value of the ratio of treated patients
delta_eps <- 0.001
pepsi <- seq(0,0.2,by=delta_eps) #variation of epsilon



conv_crit <- 0.000001

```

```{r initial_ss2, include=FALSE, cache=TRUE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times=seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       { 
         dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        
        list(c(dS, dIw, dIz))
       })
}


parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_eps=function(x) {
  parameters[5] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_eps <- do.call(rbind, lapply(pepsi, exploit_param_eps))
steady_eps <- unlist(steady_eps)

steady_time_eps <- steady_eps[,1]
steady_S_eps <- steady_eps[,2]
steady_Iw_eps <- steady_eps[,3]
steady_Iz_eps <- steady_eps[,4]
steady_p_eps <- steady_eps[,4]/(steady_eps[,4]+steady_eps[,3])

table_ss <- cbind(steady_S_eps, steady_Iw_eps, steady_Iz_eps)
```


```{r initial_ss_plot2, echo=FALSE, cache=TRUE}
plot(pepsi, steady_Iz_eps, main="Starting with a steady state \n corresponding to eps=0.20", xlab="AMU", ylab="proportion", ylim=c(0,1), lty=2, lwd=2, type="l", col='red')
lines(pepsi, steady_Iw_eps, lty=3, lwd=2, type='l', col='red')
lines(pepsi, steady_S_eps, lty=1, lwd=2, type='l', col='red')
lines(pepsi, steady_p_eps, lty=1, lwd=2, type='l', col='black')


legend("bottomleft" , inset=.05, c("S", "Iz", "Iw", "p"), lty=c(1,2,3,1), lwd=c(2,2,2,2), col=c(rep('red',3), 'black'))
```


```{r initial_ss_tables_prep2, echo=FALSE, cache=TRUE}


change_up_ss <- matrix(c(unlist(table_ss[1:(nrow(table_ss)-2),]), seq(delta_eps, (0.20-delta_eps), by=delta_eps)), ncol=4)

change_down_ss <- matrix(c(unlist(table_ss[3:(nrow(table_ss)),]), seq(delta_eps, 0.20-delta_eps, by=delta_eps)), ncol=4)
```

```{r time_to_stabilization2, echo=FALSE}
#somehow doesn't work, I cannot subset in apply...


#time_to_change=function(x) {
#  parameters[5] <- x[4]
#  state[1] <- x[1]
#  state[2] <- x[2]
#  state[3] <- x[3]
#  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
#  return(tail(out, n=1))
#}

#change_up_ss <- matrix(unlist(change_up_ss), ncol=4)

#out_up <- apply(change_up_ss, 1, time_to_change)


#out_up <- do.call(rbind, apply(change_up_ss2, 1, time_to_change))

#out_up <- do.call(rbind, apply(change_up_ss, 1, time_to_change))
#out_down <- do.call(rbind, apply(change_down_ss, 1, time_to_change))


out_up <- rep(0,4)

for (i in 1:nrow(change_up_ss)) {
  parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)
  state <- c(S=1-2*prop, Iw=prop, Iz=prop)
  parameters[5] <- change_up_ss[i,4]
  state[1] <- change_up_ss[i,1]
  state[2] <- change_up_ss[i,2]
  state[3] <- change_up_ss[i,3]
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  out_up <- rbind(out_up, tail(out,1))
}

out_down <- rep(0,4)

for (i in 1:nrow(change_down_ss)) {
  parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)
  state <- c(S=1-2*prop, Iw=prop, Iz=prop)
  parameters[5] <- change_down_ss[i,4]
  state[1] <- change_down_ss[i,1]
  state[2] <- change_down_ss[i,2]
  state[3] <- change_down_ss[i,3]
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  out_down <- rbind(out_down, tail(out,1))
}



```

```{r time_to_stabilization_plot2, echo=FALSE}


time_up <- out_up[2:nrow(out_up),1]

time_down <- out_down[2:nrow(out_down),1]

pepsi_change <- seq(delta_eps, (0.20-delta_eps), by=delta_eps)

plot(pepsi_change, time_up, main="Inertia", xlab="proportion of treated patients", ylab="time to stabilization", lwd=2, col='red', type='l')
lines(pepsi_change, time_down, lwd=2, col='blue', type='l')

legend("bottomleft" , inset=.05, c("Increasing eps", "Decreasing eps"), lwd=c(2,2), col=c('red', 'blue'))
```

