---
title: "Supermodel"
author: "Jakub"
date: "18 října 2016"
output: html_document
---

```{r param, include=FALSE}
library(deSolve)

options("scipen" = 10)
N <- 1
a <- 10000 #time span
m <- 1 #time step

pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

peps <- 0.10 #initial value of the ratio of treated patients

pc_zw <- 0.5  # competitivity ratio : probability of replacement of Iz by Iw when reinfected and not treated
pc_wz <- 0.02



prhoi <- seq(0,0.10,by=0.001)
pepsi <- seq(0,1,by=0.01)
pc_wzi <- seq(0,0.10, by=0.001)
pc_zwi <- seq(0,0.80, by=0.001)

prop <- 0.01 



conv_crit <- 0.00001


```



\begin{aligned}

\frac{dS}{dt} &=- {\beta_w} {I_w}{S} - {\beta_z} {I_z} {S} + {\gamma}  {I_z} + {\gamma}(1 - {\epsilon}){I_w} + {\gamma `}  {\epsilon}  {I_w} \\

\frac{dI_w}{dt} &={\beta_w} {I_w}{S} + {c}(1-{\epsilon})\beta_w{I_w}{I_z} - {\gamma}(1 - {\epsilon}){I_w} - {\gamma `}  {\epsilon}  {I_w} - ((1-{c}) (1-{\epsilon}) + \epsilon) {\beta_z}{I_z}{I_w} - {\rho}{\epsilon}{I_w} \\

\frac{dI_z}{dt} &={\beta_z} {I_z}{S} + ((1-{c})(1-{\epsilon}) + \epsilon) {\beta_z}{I_z}{I_w} + {\rho}{\epsilon}{I_W} - {\gamma}  {I_z} - {c}(1-{\epsilon})\beta_w{I_w}{I_z} \\


 \end{aligned}
 
```{r trial, include=FALSE, cache=TRUE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho, c_zw=pc_zw, c_wz=pc_wz)

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       {dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + c_zw*(1-eps)*beta_w*Iw*Iz - (c_wz*(1-eps)+eps)*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + (c_wz*(1-eps)+eps)*beta_z*Iz*Iw + rho*eps*Iw - c_zw*(1-eps)*beta_w*Iw*Iz - gamma*Iz
        
        list(c(dS, dIw, dIz))
       })
}

out=as.data.frame(
  ode(y=state, times=times, func=SIS, parms=parameters)
)

```


```{r main_trial, echo=FALSE, fig.align='center'}

plot(times, out$S, main="Trial", xlab="time (steps)", ylab="ratio", ylim=c(0,1), lty=1, lwd=2, type="l")
lines(times, out$Iw, lty=3, lwd=2)
lines(times, out$Iz, lty=2, lwd=2)

legend("topleft" , inset=.05, c("S Susceptible","Iw Sensitive strain", "Iz Resistant strain"), lty=c(1,3,2), lwd=c(2,2,2))
```




``` {r steady_state_eps, include=FALSE, cache=TRUE}

parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho, c_zw=pc_zw, c_wz=pc_wz )

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_eps=function(x) {
  parameters[5] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_eps <- do.call(rbind, lapply(pepsi, exploit_param_eps))
steady_eps <- unlist(steady_eps)

steady_time_eps <- steady_eps[,1]
steady_S_eps <- steady_eps[,2]
steady_Iw_eps <- steady_eps[,3]
steady_Iz_eps <- steady_eps[,4]

```

```{r steady_state_eps_plot, echo=FALSE}

plot(pepsi, steady_Iw_eps, main="Steady-states : treatment variations", xlab="proportion of treated patients", ylab="ratio", ylim=c(0,1), lty=3, lwd=2, type="l")

lines(pepsi, steady_Iz_eps, lty=2, lwd=2)
lines(pepsi, steady_S_eps, lty=1, lwd=2)

legend("topright" , inset=.05, c("Iw Sensitive strain", "Iz Resistant strain", "S Susceptible population" ), lty=c(3,2,1), lwd=c(2,2,2))

```

``` {r steady_state_rho, include=FALSE, cache=TRUE}

parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho, c_zw=pc_zw, c_wz=pc_wz )

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_rho=function(x) {
  parameters[6] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_rho <- do.call(rbind, lapply(prhoi, exploit_param_rho))
steady_rho <- unlist(steady_rho)

steady_time_rho <- steady_rho[,1]
steady_S_rho <- steady_rho[,2]
steady_Iw_rho <- steady_rho[,3]
steady_Iz_rho <- steady_rho[,4]

```

```{r steady_state_rho_plot, echo=FALSE, fig.align='center'}
plot(prhoi, steady_Iw_rho, main="Steady-states : treatment failure variations", xlab="proportion of treatment failures", ylab="ratio", ylim=c(0,1), lty=3, lwd=2, type="l")

lines(prhoi, steady_Iz_rho, lty=2, lwd=2)
lines(prhoi, steady_S_rho, lty=1, lwd=2)

legend("topright" , inset=.05, c("Iw Sensitive strain", "Iz Resistant strain", "S Susceptible population" ), lty=c(3,2,1), lwd=c(2,2,2))

```


``` {r steady_state_w_to_z_inf, include=FALSE, cache=TRUE}

parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho, c_zw=pc_zw, c_wz=pc_wz )

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_c_wz=function(x) {
  parameters[8] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_c_wz <- do.call(rbind, lapply(pc_wzi, exploit_param_c_wz))
steady_c_wz <- unlist(steady_c_wz)

steady_time_c_wz <- steady_c_wz[,1]
steady_S_c_wz <- steady_c_wz[,2]
steady_Iw_c_wz <- steady_c_wz[,3]
steady_Iz_c_wz <- steady_c_wz[,4]

```

```{r steady_state_w_to_z_plot, echo=FALSE, fig.align='center'}
plot(pc_wzi, steady_Iw_c_wz, main="Steady-states : replacement of Iw by Iz rate variations", xlab="rate of successful replacement of Iw by Iz in treated patients", ylab="ratio", ylim=c(0,1), lty=3, lwd=2, type="l")

lines(pc_wzi, steady_Iz_c_wz, lty=2, lwd=2)
lines(pc_wzi, steady_S_c_wz, lty=1, lwd=2)

legend("topright" , inset=.05, c("Iw Sensitive strain", "Iz Resistant strain", "S Susceptible population" ), lty=c(3,2,1), lwd=c(2,2,2))

```


``` {r steady_state_z_to_w_inf, include=FALSE, cache=TRUE}

parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho, c_zw=pc_zw, c_wz=pc_wz )

state <- c(S=1-2*prop, Iw=prop, Iz=prop)

times <- seq(0, a, by=m)


root_main=function(times, state, parameters){
  dstate <- unlist(SIS(times, state, parameters))
  sum(abs(dstate)) - conv_crit
  }

exploit_param_c_zw=function(x) {
  parameters[7] <- x
  out <- lsodar(func=SIS, y=state, parms=parameters, times=times, rootfunc=root_main)
  return(tail(out, n=1))
  }

steady_c_zw <- do.call(rbind, lapply(pc_zwi, exploit_param_c_zw))
steady_c_zw <- unlist(steady_c_zw)

steady_time_c_zw <- steady_c_zw[,1]
steady_S_c_zw <- steady_c_zw[,2]
steady_Iw_c_zw <- steady_c_zw[,3]
steady_Iz_c_zw <- steady_c_zw[,4]

```

```{r steady_state_z_to_w_plot, echo=FALSE, fig.align='center'}
plot(pc_zwi, steady_Iw_c_zw, main="Steady-states : replacement of Iz by Iw rate variations", xlab="rate of successful replacement of Iz by Iw in untreated patients", ylab="ratio", ylim=c(0,1), lty=3, lwd=2, type="l")

lines(pc_zwi, steady_Iz_c_zw, lty=2, lwd=2)
lines(pc_zwi, steady_S_c_zw, lty=1, lwd=2)

legend("topright" , inset=.05, c("Iw Sensitive strain", "Iz Resistant strain", "S Susceptible population" ), lty=c(3,2,1), lwd=c(2,2,2))

```