---
title: "Determination of d(Iz/(Iw+Iz))/dt"
author: "Jakub"
date: "24 října 2016"
output: html_document
---

The model is defined by following equations:

$$
\begin{aligned}
\frac{dS}{dt} &=- \beta_w I_wS - \beta_z I_z S + \gamma  I_z + \gamma(1 - \varepsilon)I_w + \gamma `  \varepsilon  I_w \\
\frac{dI_w}{dt} &=\beta_w I_wS + (1-\varepsilon)\beta_wI_wI_z - \gamma(1 - \varepsilon)I_w - \gamma `  \varepsilon  I_w - \varepsilon\beta_zI_zI_w - \rho\varepsilon I_w \\
\frac{dI_z}{dt} &=\beta_z I_zS + \varepsilon\beta_zI_zI_w + \rho\varepsilon I_w - \gamma  I_z - (1-\varepsilon)\beta_wI_wI_z \\
\end{aligned}
$$
Therefore we have:
$$
\begin{aligned}
\frac{\frac {dI_z}{dM}}{dt} &= -\beta_zI_z(1-\varepsilon) + \varepsilon\beta_wI_z + \frac{1}{M} \left( I_z\varepsilon(\gamma` - \gamma) +  I_z(\beta_z-\beta_w) - \beta_wI_z^{2}\varepsilon + \beta_z I_z^{2}(1-\varepsilon) \right) + \frac{I_z^{2}}{M^{2}} \left(\beta_w-\beta_z+\varepsilon(\gamma-\gamma`) \right)+ \frac{M-I_z}{M}\rho\varepsilon \\
\end{aligned}
$$
Where:
$$
\begin{aligned}
M=I_z+I_w
\end{aligned}
$$

```{r param, include=FALSE}
library(deSolve)

options("scipen" = 10)
N <- 1
a <- 10000 #time span
m <- 1 #time step

pbeta_w <- 0.04 #transmission parameter of Iw
pbeta_z <- 0.015 #transmission parameter of Iz

pgammaa <- 0.01 #innate recovery rate
pgamma_tilt <- 0.1 #recovery rate of Iw when treated by antibiotics


prho <- 0.05 #probability of clinical failure

peps <- 0.10 #initial value of the ratio of treated patients

pc_zw <- 0.5  # competitivity ratio : probability of replacement of Iz by Iw when reinfected and not treated
pc_wz <- 0.02 # competitivity ratio : probability of replacement of Iw by Iz when reinfected and not treated



prhoi <- seq(0,0.10,by=0.001)
pepsi <- seq(0,1,by=0.01)
pc_wzi <- seq(0,0.10, by=0.001)
pc_zwi <- seq(0,0.80, by=0.001)

prop <- 0.01 



conv_crit <- 0.00001

```

```{r trial, include=FALSE, cache=TRUE}
parameters <- c(beta_w=pbeta_w, beta_z=pbeta_z, gamma=pgammaa, gamma_prim=pgamma_tilt, eps=peps, rho=prho)

state <- c(S=1-2*prop, Iw=prop, Iz=prop, Iz_div_Inf=0.5)

times <- seq(0, a, by=m)

SIS=function(times, state, parameters){
  with(as.list(c(state,parameters)),
       {dS = - beta_w*Iw*S - beta_z*Iz*S + gamma*(1-eps)*Iw + gamma_prim*eps*Iw + gamma*Iz
        dIw = beta_w*Iw*S + (1-eps)*beta_w*Iw*Iz - eps*beta_z*Iz*Iw - rho*eps*Iw - gamma*(1-eps)*Iw - gamma_prim*eps*Iw
        dIz = beta_z*Iz*S + eps*beta_z*Iz*Iw + rho*eps*Iw - (1-eps)*beta_w*Iw*Iz - gamma*Iz
        dIz_div_Inf = -beta_z*Iz*(1-eps)+eps*beta_w*Iz+(1/(Iz+Iw))*(beta_z*Iz*Iz*(1-eps)+Iz*(beta_z-beta_w)-Iz*Iz*beta_w*eps+Iz*eps*(gamma_prim-gamma)) + (1/((Iz+Iw)*(Iz+Iw)))*(Iz*Iz*(beta_w-beta_z)+Iz*Iz*eps*(gamma-gamma_prim))+rho*eps*Iw/(Iz+Iw)
        list(c(dS, dIw, dIz, dIz_div_Inf))
        })
  }
#dIz_div_Inf = (1/(Iz+Iw))*(beta_z*Iz*(1-Iz-Iw)+eps*beta_z*Iw*Iz+rho*eps*Iw-gamma*Iz-(1-eps)*beta_w*Iw*Iz)+(1/((Iw+Iz)*(Iw+Iz)))*Iz*(-beta_w*Iw*(1-Iz-Iw)-beta_z*Iz*(1-Iz-Iw)+gamma*Iz+gamma*(1-eps)*Iw+gamma_prim*eps*Iw)

out=as.data.frame(
  ode(y=state, times=times, func=SIS, parms=parameters)
)

require(plyr)
out2 <- cbind(out, mutate(out, new=out$Iz/(out$Iw+out$Iz)))

```

